services:

  postgresql:
    env_file: .env
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - prod-backend


  redis:
    env_file: .env
    hostname: ${REDIS_HOST}
    command: redis-server --requirepass "${REDIS_PASS}"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - prod-backend


  backend:
    env_file: .env
    build:
      target: production
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:60707"
    networks:
      - prod-backend


  frontend:
    env_file: .env
    build:
      target: production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - node_env=development
    ports:
      - "${FRONTEND_PORT}:60808"
    depends_on:
      backend:
        condition: service_started
    networks:
      - prod-frontend
      - prod-backend


networks:
  prod-frontend:
    internal: false
  prod-backend:
    internal: false
