---
services:

  postgresql:
    env_file: .env.dev
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - dev-backend


  redis:
    env_file: .env
    hostname: ${REDIS_HOST}
    command: redis-server --requirepass "${REDIS_PASS:-}"
    networks:
      - dev-backend


  backend:
    env_file: .env.dev
    build:
      target: development
    volumes:
      - ./backend:/app
    ports:
      - "3030:3030"
    networks:
      - dev-backend


  frontend:
    env_file: .env.dev
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - node_env=development
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - dev-frontend
      - dev-backend


networks:
  dev-frontend:
    internal: false
  dev-backend:
    internal: false
