services:

  postgresql:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 3


  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ./data/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 3


  backend:
    restart: unless-stopped
    build:
      context: ./backend
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy


  frontend:
    restart: unless-stopped
    build:
      context: ./frontend

