---
services:

  postgresql:
    env_file: .env.dev
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "15432:5432"
    networks:
      - dev-network


  redis:
    env_file: .env.dev
    hostname: ${REDIS_HOST}
    command: redis-server --requirepass "${REDIS_PASS}"
    ports:
      - "16379:6379"
    networks:
      - dev-network


  backend:
    env_file: .env.dev
    build:
      target: development
    volumes:
      - ./backend:/app
    ports:
      - "3030:3030"
    networks:
      - dev-network


  frontend:
    env_file: .env.dev
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - node_env=development
    ports:
      - "3000:3000"
    networks:
      - dev-network


networks:
  dev-network:
    internal: false
